### ISSUE TITLE
私のサイトの移転による、リンクの書き換えのお願いについて

### ISSUE THREAD

**Issue by natumi-kaoru** [chainsawsteel1/chainsawsteel1.github.io#3]
平素よりお世話になっております。この度、サイトの所在地を変更することとなりましたのでお伝えいたします。お手数ですが、リンクのアドレスを書き換えてくださると幸甚に存じます。

記

移転先URL： https://natumi.tkngh.jp

**Comment by chainsawsteel1** [comment]
変更が完了しました。
デプロイが完了次第反映されます。

**Comment by natumi-kaoru** [comment]
ありがとうございます。ただいま公開いたしました。
任意にCloseいただいて構いません。
